/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.*;
import java.lang.*;

/**

 @author Nick
 */
public class TransactionManager extends javax.swing.JFrame
{

   ButtonGroup accountType;
   BankDatabase db;
   Account account;
   int accNumber;
   String number;
   boolean isDeposit = false;

   /**
    Creates new form TransactionManager
    */
   public TransactionManager()
   {
      initComponents();
      accountType = new ButtonGroup();
      addRadio();
      db = new BankDatabase();
   }

   private void addRadio()
   {
      accountType.add(radCheck);
      accountType.add(radSav);
      accountType.add(radMM);
   }

   private void addAccount(String newName, String newPhone)
   {
      if (radPosition())
      {
         if (radCheck.isSelected())
         {
            account = new Checking(newName, newPhone, deposit.isSelected());
         }
         else if (radSav.isSelected())
         {
            account = new Savings(newName, newPhone, specialSav.isSelected());
         }
         else if (radMM.isSelected())
         {
            account = new MoneyMarket(newName, newPhone);
         }
         if (db.contains(account))
         {
            JOptionPane.showMessageDialog(this,"Person already has account",
               "Unsuccessful Add", JOptionPane.ERROR_MESSAGE); 
         }
         else
         {
            db.add(account);
            JOptionPane.showMessageDialog(this,"Account successfully opened!",
               "Successful Add", JOptionPane.INFORMATION_MESSAGE);
         }
         
      }

   }

   private boolean radPosition()
   {
      if (!radCheck.isSelected() && !radSav.isSelected()
            && !radMM.isSelected())
      {
         JOptionPane.showMessageDialog(this, "Please select an account type",
               "Error Message", JOptionPane.ERROR_MESSAGE);
         return false;
      }
      return true;
   }

   private boolean check(String newPhone, String newName)
   {
      if (!isInteger(newPhone))
      {
         JOptionPane.showMessageDialog(this, "Please enter a valid phone "
               + "number!",
               "Error Message", JOptionPane.ERROR_MESSAGE);
         phone.setText("");
         return false;
      }
      if (!isName(newName))
      {
         JOptionPane.showMessageDialog(this, "Please enter a valid name ",
               "Error Message", JOptionPane.ERROR_MESSAGE);
         name.setText("");
         return false;
      }

      return true;
   }

   private boolean isName(String input)
   {
      try
      {
         Integer.parseInt(input);
         return false;
      }
      catch (Exception e)
      {
         return true;
      }
   }

   private boolean isInteger(String input)
   {
      try
      {
         Integer.parseInt(input);
         return true;
      }
      catch (Exception e)
      {
         return false;
      }

   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      name = new javax.swing.JTextField();
      phone = new javax.swing.JTextField();
      balText = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      accText = new javax.swing.JTextField();
      dateText = new javax.swing.JTextField();
      jPanel2 = new javax.swing.JPanel();
      radCheck = new javax.swing.JRadioButton();
      deposit = new javax.swing.JCheckBox();
      jPanel3 = new javax.swing.JPanel();
      radSav = new javax.swing.JRadioButton();
      specialSav = new javax.swing.JCheckBox();
      jPanel4 = new javax.swing.JPanel();
      radMM = new javax.swing.JRadioButton();
      jLabel6 = new javax.swing.JLabel();
      jTextField6 = new javax.swing.JTextField();
      open = new javax.swing.JButton();
      close = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      showText = new javax.swing.JButton();
      jButton6 = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      bankInfo = new javax.swing.JTextArea();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Transaction Manager");

      jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      jLabel1.setText("Name");

      jLabel2.setText("Phone");

      jLabel3.setText("Balance");

      balText.setEditable(false);

      jLabel4.setText("Account #");

      jLabel5.setText("Opened On");

      accText.setEditable(false);

      dateText.setEditable(false);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(balText))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phone)))
                  .addGap(45, 45, 45)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(accText)
                     .addComponent(dateText))))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4)
               .addComponent(accText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5)
               .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(24, 24, 24)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(balText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(35, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      radCheck.setText("Checking");
      radCheck.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            radCheckActionPerformed(evt);
         }
      });

      deposit.setText("Direct Deposit");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(radCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(60, 60, 60)
            .addComponent(deposit)
            .addContainerGap(73, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(radCheck)
               .addComponent(deposit))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      radSav.setText("Savings");
      radSav.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            radSavActionPerformed(evt);
         }
      });

      specialSav.setText("Special Savings Account");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(radSav, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
            .addComponent(specialSav)
            .addGap(43, 43, 43))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(radSav)
               .addComponent(specialSav))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      radMM.setText("Money Market");
      radMM.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            radMMActionPerformed(evt);
         }
      });

      jLabel6.setText("# of withdrawls");

      jTextField6.setEditable(false);

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(radMM)
            .addGap(129, 129, 129)
            .addComponent(jLabel6)
            .addGap(18, 18, 18)
            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(radMM)
               .addComponent(jLabel6)
               .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      open.setText("Open New");
      open.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            openActionPerformed(evt);
         }
      });

      close.setText("Close Existing");
      close.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            closeActionPerformed(evt);
         }
      });

      jButton3.setText("Withdraw");

      jButton4.setText("Deposit");

      showText.setText("Show All Accounts");
      showText.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            showTextActionPerformed(evt);
         }
      });

      jButton6.setText("Run Monthly Interest and Fee");

      bankInfo.setColumns(20);
      bankInfo.setRows(5);
      jScrollPane1.setViewportView(bankInfo);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(showText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(open, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(21, 21, 21)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(open)
               .addComponent(close)
               .addComponent(jButton4)
               .addComponent(jButton3))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(showText)
               .addComponent(jButton6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void openActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openActionPerformed
   {//GEN-HEADEREND:event_openActionPerformed
      String newName = name.getText();
      String newPhone = phone.getText();

      if (newName.isEmpty())
      {
         JOptionPane.showMessageDialog(this, "No name entered!",
               "Error Message", JOptionPane.ERROR_MESSAGE);
      }
      if (newPhone.isEmpty())
      {
         JOptionPane.showMessageDialog(this, "No phone number entered!",
               "Error Message", JOptionPane.ERROR_MESSAGE);
      }
      if (!newName.isEmpty() && !newPhone.isEmpty())
      {
         if (check(newPhone, newName))
         {
            addAccount(newName, newPhone);
            accText.setText(String.valueOf(account.getAccNum()));
            dateText.setText(account.getDate());
            balText.setText("$" + String.valueOf(account.getBalance()));
         }

      }
   }//GEN-LAST:event_openActionPerformed

   private void closeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeActionPerformed
   {//GEN-HEADEREND:event_closeActionPerformed
      String newName = name.getText();
      String newPhone = phone.getText();
      account = new MoneyMarket(newName, newPhone);
      if (db.size() == 0)
      {
         JOptionPane.showMessageDialog(this, "No accounts in database",
               "Error Message", JOptionPane.ERROR_MESSAGE);
      }
      else
      {
         if (newName.isEmpty())
         {
            JOptionPane.showMessageDialog(this, "No name entered!",
                  "Error Message", JOptionPane.ERROR_MESSAGE);
         }
         if (newPhone.isEmpty())
         {
            JOptionPane.showMessageDialog(this, "No phone number entered!",
                  "Error Message", JOptionPane.ERROR_MESSAGE);
         }
         if (!newName.isEmpty() && !newPhone.isEmpty())
         {
            if (db.contains(account))
            {
               db.remove(account);
               JOptionPane.showMessageDialog(this, "Account removed!",
                     "Close Message", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
               JOptionPane.showMessageDialog(this, "Account not found!",
                     "Error Message", JOptionPane.ERROR_MESSAGE);
            }
         }
      }
   }//GEN-LAST:event_closeActionPerformed

   private void showTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showTextActionPerformed
   {//GEN-HEADEREND:event_showTextActionPerformed
      bankInfo.setText("");
      bankInfo.append(db.size() + " Accounts\n");
      bankInfo.append(db.toString());
      
   }//GEN-LAST:event_showTextActionPerformed

   private void radCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radCheckActionPerformed
   {//GEN-HEADEREND:event_radCheckActionPerformed
      deposit.setEnabled(true);
      specialSav.setEnabled(false);
   }//GEN-LAST:event_radCheckActionPerformed

   private void radSavActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radSavActionPerformed
   {//GEN-HEADEREND:event_radSavActionPerformed
      specialSav.setEnabled(true);
      deposit.setEnabled(false);
   }//GEN-LAST:event_radSavActionPerformed

   private void radMMActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radMMActionPerformed
   {//GEN-HEADEREND:event_radMMActionPerformed
      specialSav.setEnabled(false);
      deposit.setEnabled(false);
   }//GEN-LAST:event_radMMActionPerformed

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try
      {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
         {
            if ("Nimbus".equals(info.getName()))
            {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex)
      {
         java.util.logging.Logger.getLogger(TransactionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex)
      {
         java.util.logging.Logger.getLogger(TransactionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex)
      {
         java.util.logging.Logger.getLogger(TransactionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex)
      {
         java.util.logging.Logger.getLogger(TransactionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new TransactionManager().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField accText;
   private javax.swing.JTextField balText;
   private javax.swing.JTextArea bankInfo;
   private javax.swing.JButton close;
   private javax.swing.JTextField dateText;
   private javax.swing.JCheckBox deposit;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton6;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextField jTextField6;
   private javax.swing.JTextField name;
   private javax.swing.JButton open;
   private javax.swing.JTextField phone;
   private javax.swing.JRadioButton radCheck;
   private javax.swing.JRadioButton radMM;
   private javax.swing.JRadioButton radSav;
   private javax.swing.JButton showText;
   private javax.swing.JCheckBox specialSav;
   // End of variables declaration//GEN-END:variables
}
